config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  post 'search/user' => 'users#search', as: :search_user
  resources :pages do
    post 'add_role' => 'pages#add_role', as: :add_role
  end
  resources :relationships, only: %i[create destroy]

  resources :requests, only: %i[create index update destroy]
  resources :follows, only: %i[create destroy]
  resources :users, only: %i[show index]

  concern :imageable do
    resources :photos, only: [:new]
  end

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, only: %i[show create update destroy edit], concerns: %i[imageable likeable] do
    resources :comments, only: %i[edit create destroy update]
  end

  resources :comments, only: %i[edit create destroy update], concerns: :likeable
  resources :stories, only: %i[show create destroy], concerns: :imageable

  resources :subscriptions, only: %i[new create index]
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, dependent: :destroy, as: :likeable

  validates :user_id, :post_id, :body, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# controller to manage comments
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %i[edit create destroy update]
  before_action :find_comment, only: %i[edit destroy update]
  after_action :verify_authorized, only: %i[edit destroy update]

  def create
    @comment = @post.comments.create(comment_params.merge({ user_id: current_user.id }))
    authorize @comment
    if @comment.body.blank?
      flash[:alert] = 'Cannot add empty comment!'
      redirect_to @post
    elsif @comment.save
      respond_to :js
    end
  end

  def edit
    authorize @comment
  end

  def update
    authorize @comment
    redirect_to @post
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated!'
    else
      flash[:alert] = 'Error occurred while updating the comment!'
    end
  end

  def destroy
    authorize @comment
    respond_to :js if @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.find_by(id: params[:post_id])
    return if @post

    flash[:alert] = 'Post not found!'
    redirect_to root_path
  end

  def find_comment
    @comment = Comment.find_by(id: params[:id])
    return if @comment

    flash[:alert] = 'Comment not found!'
    redirect_to root_path
  end

  def save_comment
    if @comment.save
      flash[:notice] = 'Commented!'
    else
      flash[:alert] = 'Error occurred while adding the comment!'
    end
    redirect_to @post
  end
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="comment-col">
    <%= link_to comment.user.fullname, user_path(comment.user.id), class: "btn post-username" %>
    <%= comment.body %>
  </div>
  <% if comment.user == current_user or post.user == current_user %>
    <div class="comment-col options-comment">
      <% if comment.user == current_user %>
        <%= link_to edit_post_comment_path(post, comment), method: :get, class: "homepage-post-btn" do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <% end %>
      <% end %>
      <%= link_to post_comment_path(post, comment), data: { confirm: "Delete this Comment?" },
                  method: :delete, class: "homepage-post-btn", remote: true do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
      <%= link_to comment_likes_path(comment), method: :post, remote: true, class: "homepage-post-btn" do %>
        <i class="fa-solid fa-heart"></i>
      <% end %>
    </div>
  <% end %>
  <a class="comment-time">
    <% comment_time = time_ago_in_words(comment.created_at)  %>
    <% if comment_time == 'less than a minute' %>
      <%= 'Just now'%>
    <% else %>
      <%= comment_time %>
    <% end %>
  </a>
  <div id="like-Comment-<%= comment.id.to_s %>" class="likes-comment">
    <%= render "likes/like", parent: comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [post, post.comments.build ], remote:true do |f| %>
  <%= f.text_field :body, placeholder: "Add a comment...", class: "text_field post-comment",
                   autocomplete: :off, required: true, pattern: "^[^-\s][a-zA-Z0-9_\s-]+$",
                   title: "First character can not be a space!"%>
  <%= f.submit "Post", class: "btn submit-comment" %>
<% end %>

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
html('<%= j render @post.comments, post: @post %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_body').val("");
console.log("new comment success");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
html('<%= j render @post.comments, post: @post %>');
console.log("delete comment success");

app/views/comments/edit.html.erb
<div class="edit-post text-center">
  <%= form_for :comment, { :url => post_comment_path(@post, @comment), :method => :patch } do |f| %>
    <%= f.label :body, class: "control-label" %>
    <%= f.text_field :body, class: "text_field", required: true, pattern: "^[^-\s][a-zA-Z0-9_\s-]+$",
                     title: "First character can not be a space!" %>
    <%= f.submit "Update", class: "btn" %>
  <% end %>
</div>