config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  post 'search/user' => 'users#search', as: :search_user
  resources :pages do
    post 'add_role' => 'pages#add_role', as: :add_role
  end
  resources :relationships, only: %i[create destroy]

  resources :requests, only: %i[create index update destroy]
  resources :follows, only: %i[create destroy]
  resources :users, only: %i[show index]

  concern :imageable do
    resources :photos, only: [:new]
  end

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, only: %i[show create update destroy edit], concerns: %i[imageable likeable] do
    resources :comments, only: %i[edit create destroy update]
  end

  resources :comments, only: %i[edit create destroy update], concerns: :likeable
  resources :stories, only: %i[show create destroy], concerns: :imageable

  resources :subscriptions, only: %i[new create index]
end

app/models/user.rb
# frozen_string_literal: true

# User class to handle accounts of users
class User < ApplicationRecord
  include Searchable

  has_many :posts, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follows, dependent: :destroy
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships
  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationships

  has_many :requests, dependent: :destroy
  has_many :sender_relationships, foreign_key: :following_id, class_name: 'Request'
  has_many :senders, through: :sender_relationships
  has_many :sending_relationships, foreign_key: :user_id, class_name: 'Request'
  has_many :sending, through: :sending_relationships

  scope :with_stories, -> { where('EXISTS(SELECT * FROM stories WHERE user_id = users.id)') }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fullname, presence: true, length: { maximum: 50 }
  validates :is_private, inclusion: { in: [true, false] }
  validates_format_of :fullname, with: /\A[a-zA-Z.']+(?: [a-zA-Z.']+){0,4}\z/

  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  def page?
    type == 'Page'
  end

  def account?
    type == 'Account'
  end

  def email_required?
    true unless page?
  end

  def password_required?
    true unless page? || password.nil?
  end

  def user_role(page_id)
    UserPageRelationship.find_by(user_id: id, page_id: page_id ).role
  end

  def add_default_avatar
    return if avatar.attached?

    avatar.attach(io: File.open(
      Rails.root.join(
        'app', 'assets', 'images', 'default-avatar.jpg'
      )
    ), filename: 'default-avatar.jpg',
                  content_type: 'image/jpg')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# app/models/user.rb
# controller to manage users
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :find_user, only: :show

  def show
    @posts = @user.posts
    @post_new = Post.new
    @story = Story.new
    @stories = @user.stories
  end

  def index
    redirect_to new_user_session_path unless user_signed_in?
    @users_with_story = User.with_stories
    @story = Story.new
    @posts = Post.all.includes(:photos)
    @post_new = Post.new
  end

  def search
    @users = User.search_like_any([:fullname], params[:search])
    render template: 'users/show-results', locals: { users: @users }
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    return if @user

    flash[:alert] = 'User not found!'
    redirect_to root_path
  end
end

app/views/users/index.html.erb
<div class="width-setter">
  <%= render 'stories/stories-box' %>
  <%= render 'posts/add-post', user_id: current_user.id  %>
  <%= render 'posts/show-all-posts' %>
</div>

app/views/users/show-results.html.erb
<div class="box-center">
  <% if users.count == 0 %>
    <div class="row search-result">
      No users found!
    </div>
  <% else %>
    <% users.each do |user| %>
      <% if users.count == 1 and user == current_user  %>
          <div class="row search-result">
            No users found!
          </div>
      <% else %>
            <% if user != current_user %>
                <div class="row search-result">
                  <%= image_tag(user.avatar, class: "thumbnail-avatar") %>
                  <%= link_to user.fullname, user_path(user.id), class: "btn post-username" %>
                </div>
            <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag @user.avatar, class: "round-image" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.fullname %></p>
      <% if @user == current_user %>
        <%= link_to "Edit profile", edit_user_registration_path, class: "btn edit-profile-btn" %>
        <button class="btn fa-solid fa-gear setting-btn" data-toggle="modal" data-target="#editPageModal"></button>
      <% elsif @user.page? and @user.accounts.include?(current_user) %>
        <%= link_to "Edit page", edit_page_path, class: "btn edit-profile-btn" %>
        <% if @user.user_role(current_user) == 'admin' %>
          <%= link_to "Manage roles", page_path(@user), class: "btn edit-profile-btn" %>
          <button class="btn fa-solid fa-gear setting-btn" data-toggle="modal" data-target="#editPageModal"></button>
        <% end %>
      <% else %>
        <% if current_user.following.include?(@user) %>
          <%= button_to "Unfollow", follow_path(id: @user.id),method: :delete, class: "btn edit-profile-btn" %>
        <% else %>
          <% if current_user.sending.include?(@user) %>
            <%= button_to "Pending Request", request_path(@user.id),
                          data: { confirm: "Are you sure? You will have to request the user again to follow!" },
                          class: "btn edit-profile-btn", method: :delete %>
          <% else %>
            <% if @user.is_private? %>
              <%= form_tag requests_path, method: :post %>
              <%= hidden_field_tag :user_id, current_user.id %>
              <%= hidden_field_tag :following_id, @user.id %>
              <%= submit_tag "Follow", class: "btn edit-profile-btn" %>
            <% else %>
              <%= button_to "Follow", follows_path(id: @user.id), class: "btn edit-profile-btn" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <% if @user.subscribed? %>
        <i class="fa-solid fa-circle-check premium-sign"></i>
      <% end %>
      <!--Modal-->
      <div class="modal fade" id="editPageModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="list-group text-center">
              <%= link_to "Get Instagram Premium", new_subscription_path(:id => @user.id),
                          class: "list-group-item list-group-item-action" %>
              <% if @user.account? %>
                <%= link_to "Create a Page", new_page_path, class: "list-group-item list-group-item-action" %>
                <%= link_to "Change Password", edit_user_registration_path,
                            class: "list-group-item list-group-item-action" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete,
                            class: "list-group-item list-group-item-action"%>
                <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!--Modal-->

    </div>
    <div class="row">
      <span class="user-info">
        <strong> <%= @user.posts.count %> </strong>
        <%= (@user.posts.count) == 1 ? 'Post' : 'Posts'%>
      </span>
      <span class="user-info">
        <strong> <%= @user.followers.count %> </strong>
        <%= (@user.followers.count) == 1 ? 'Follower' : 'Followers'%>
      </span>
      <% if @user.account? %>
        <span class="user-info">
          <strong> <%= @user.following.count %> </strong>
          <%= 'Following' %>
        </span>
      <% end %>
    </div>

    <br>
    <div>
      <% if @user.email? %>
        <div class="row">
          <p class="email"><%= @user.email %></p>
        </div>
      <% end %>
    </div>


    <div class="row">
      <p class="bio"><%= @user.bio %></p>
    </div>
  </div>
</div>

<div class="profile-width-setter">
  <%= render 'stories/stories-box' %>
  <%= render 'posts/add-post', user_id: @user.id %>
</div>

<div class="row">
  <% if @user.is_private? and @user != current_user %>
    <% if current_user.following.include?(@user) %>
      <%= render 'posts/profile-posts' %>
    <% else %>
      <% if current_user.sending.include?(@user) %>
        <div class="private-account-msg text-center">
          <strong><p> Account is private! </p></strong>
          <p> Pending follow request! </p>
        </div>
      <% else %>
        <div class="private-account-msg text-center">
          <strong><p> Account is private! </p></strong>
          <p> Follow the user to see their posts! </p>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <%= render 'posts/profile-posts' %>
  <% end %>
</div>