config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  post 'search/user' => 'users#search', as: :search_user
  resources :pages do
    post 'add_role' => 'pages#add_role', as: :add_role
  end
  resources :relationships, only: %i[create destroy]

  resources :requests, only: %i[create index update destroy]
  resources :follows, only: %i[create destroy]
  resources :users, only: %i[show index]

  concern :imageable do
    resources :photos, only: [:new]
  end

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, only: %i[show create update destroy edit], concerns: %i[imageable likeable] do
    resources :comments, only: %i[edit create destroy update]
  end

  resources :comments, only: %i[edit create destroy update], concerns: :likeable
  resources :stories, only: %i[show create destroy], concerns: :imageable

  resources :subscriptions, only: %i[new create index]
end

app/views/shared/_devise-messages.html.erb
<!--For toastr view errors -->
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
    toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>
<!--For toastr view errors -->

app/views/shared/_footer.html.erb
<br>
<br>
<br>
<!-- Footer -->

<footer class="text-center">
  <!-- Grid container -->

  <div class="container pt-4">

    <!-- Section: Links to other pages -->
    <section class="mb-1">

      <!-- Meta -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>Meta</p>
      </a>

      <!-- About -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>About</p>
      </a>

      <!-- Blog -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>Blog</p>
      </a>

      <!-- Jobs -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>Jobs</p>
      </a>

      <!-- Help -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>Help</p>
      </a>

      <!-- API -->
      <a
        class="btn btn-floating "
        href="#"
        role="button"
      >
        <p>API</p>
      </a>

      <!-- Privacy -->
      <a
        class="btn btn-floating"
        href="#"
        role="button"
      >
        <p>Privacy</p>
      </a>

    </section>
    <!-- Section: Links to other pages -->

  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center footer-font">
    © 2022 Instagram from Meta
  </div>
  <!-- Copyright -->

  <br>
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<!-- Default Navbar -->

<nav class="navbar navbar-expand-lg navbar-light">
  <!-- Logo button -->
  <%= link_to image_tag('logo.png'), root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Logo button -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- Search box -->
    <%= form_tag search_user_path, :method => "post", class: "search-form" do %>
      <%= text_field_tag :search, params[:search] , placeholder: "Search"%>
      <%= submit_tag "Search" %>
    <% end %>
    <!-- Search box -->


    <ul class="navbar-nav mr-auto ml-md-auto">
      <!-- Home page -->
      <li class="nav-item active">
        <%= link_to users_path do %>
          <i class="fa-solid fa-house nav-link active"></i>
        <% end %>
      </li>
      <!-- Home page -->

      <!-- Follow Requests -->
      <li class="nav-item active">
        <%= link_to requests_path do %>
          <i class="fa-solid fa-bell nav-link active"></i>
        <% end %>
      </li>
      <!-- Follow Requests -->

      <!-- Owned Pages -->
      <li class="nav-item active">
        <%= link_to pages_path do %>
          <i class="fa-solid fa-file-lines nav-link active"></i>
        <% end %>
      </li>
      <!-- Owned Pages -->

      <!-- Profile -->
      <li class="nav-item active">
        <%= link_to image_tag(current_user.avatar, class: "navbar-image"), user_path(current_user), class: "nav-link"  %>
      </li>
      <!-- Profile -->

    </ul>
  </div>
</nav>
<!-- Default Navbar -->