config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  post 'search/user' => 'users#search', as: :search_user
  resources :pages do
    post 'add_role' => 'pages#add_role', as: :add_role
  end
  resources :relationships, only: %i[create destroy]

  resources :requests, only: %i[create index update destroy]
  resources :follows, only: %i[create destroy]
  resources :users, only: %i[show index]

  concern :imageable do
    resources :photos, only: [:new]
  end

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, only: %i[show create update destroy edit], concerns: %i[imageable likeable] do
    resources :comments, only: %i[edit create destroy update]
  end

  resources :comments, only: %i[edit create destroy update], concerns: :likeable
  resources :stories, only: %i[show create destroy], concerns: :imageable

  resources :subscriptions, only: %i[new create index]
end

app/views/pages/_assigned-roles.html.erb
<div class="info-box">
  <% @page.accounts.each do |account| %>
    <div class="row">
      <div class="info-col">
        <%= image_tag(account.avatar, class: "thumbnail-avatar") %>
        <%= link_to account.fullname, user_path(account), class: "btn post-username" %>
      </div>

      <div class="role">
        <a class="role-text"><%= @page.user_role(account) %></a>
        <%= link_to relationship_path(:id => @page.id, :account => account.id), data: { confirm: "Delete this post?" },
                    method: :delete, class: "homepage-post-btn" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_form.html.erb
<%= form_for @page, :html => {:multipart => true} do |f| %>

  <!-- Message to display -->
  <h6>
    <strong> Create your page & connect with millions of users! </strong>
  </h6>
  <!-- Message to display -->

  <br>

  <!-- Form fields -->
  <div class="form-group">
    <span class="form-header"> Change Page Photo </span>
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :fullname, autofocus: true, placeholder: "Name", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.text_area :bio, placeholder: "Description", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Create Page", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pages/edit.html.erb
<div class="main-form">
  <div class="container">
    <div class="text-left">
      <div class="box-center">
        <%= form_for :page, { :url => page_path, :method => :patch } do |f| %>
          <div class="form-group">
            <%= image_tag(@page.avatar, class: "image-edit") %>
            <a class="form-fullname"><%= @page.fullname %></a>
          </div>

          <div class="form-group">
            <span class="form-header"> Change Page Photo </span>
            <%= f.file_field :avatar, class: "form-control" %>
          </div>

          <div class="form-group">
            <span class="form-header"> Name </span>
            <%= f.text_field :fullname, autofocus: true, autocomplete: "Name", class: "form-control"%>
          </div>

          <div class="form-group">
            <span class="form-header"> Bio </span>
            <%= f.text_area :bio, autofocus: true, class: "form-control"%>
          </div>

          <div class="actions">
            <%= f.submit "Update", class: "btn btn-primary" %>
          </div>

        <% end %>

        <% if @page.user_role(current_user) == 'admin' %>
            <span class="form-header del-acc"> Delete account?
              <%= button_to "Delete Page", page_path(@page), data: { confirm: "Are you sure?" },
                            method: :delete, class: "btn btn-primary" %>
            </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="info-box">
  <% if current_user.pages.count < 1 %>
    <div class="row text-center">
      <span class="request-text">
        No pages owned!
      </span>
    </div>
  <% else %>
    <% current_user.pages.each do |page| %>
      <div class="row">
        <div class="info-col">
          <%= image_tag(page.avatar, class: "thumbnail-avatar") %>
          <%= link_to page.fullname, user_path(page), class: "btn post-username" %>
        </div>

        <div class="role">
        <a><%= current_user.user_role(page) %></a>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/new.html.erb
<div class="main-form">
  <div class="container">
    <div class="text-left">
      <div class="box-center">
        <%= render "pages/form" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<%= render 'pages/assigned-roles' %>

<div class="main-form">
  <div class="container">
    <div class="add-role">
      <%= form_for :relation, url: relationships_url do |f| %>
        <h5>
          <strong> Add a new role </strong>
        </h5>

        <div class="form-group">
          <span class="form-header"> Email of user </span>
          <%= f.text_field :email, class: "form-control"%>
        </div>

        <div class="form-group">
          <span class="form-header"> Role </span>
          <%= f.select :role, %w[admin editor]%>
        </div>

        <div class="field">
          <%= f.hidden_field :id, value: @page.id %>
        </div>

        <div class="actions">
          <%= f.submit "Add Role", class: "btn btn-primary" %>
        </div>
      <% end  %>
    </div>
  </div>
</div>